USE [COLEGIO_TIYOLI]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESTATUS_T](
	[ID_EST] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_EST] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_EST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERMISOS_T](
	[ID_PER] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_PER] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIOS_T](
	[ID_US] [int] IDENTITY(1,1) NOT NULL,
	[CORREO_US] [varchar](260) NULL,
	[CONTRASENA_US] [varchar](260) NULL,
	[NOMBRE_US] [varchar](100) NULL,
	[APELLIDO_P_US] [varchar](100) NULL,
	[APELLIDO_M_US] [varchar](100) NULL,
	[PERMISOS_US] [int] NULL,
	[ESTATUS_US] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_US] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USUARIOS_T]  WITH CHECK ADD  CONSTRAINT [FK_ESTATUS] FOREIGN KEY([ESTATUS_US])
REFERENCES [dbo].[ESTATUS_T] ([ID_EST])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[USUARIOS_T] CHECK CONSTRAINT [FK_ESTATUS]
GO

ALTER TABLE [dbo].[USUARIOS_T]  WITH CHECK ADD  CONSTRAINT [FK_PERMISOS] FOREIGN KEY([PERMISOS_US])
REFERENCES [dbo].[PERMISOS_T] ([ID_PER])
GO

ALTER TABLE [dbo].[USUARIOS_T] CHECK CONSTRAINT [FK_PERMISOS]
GO

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PUBLICACIONES_T](
	[ID_PUB] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION_PUB] [varchar](max) NULL,
	[IMAGENES_PUB] [varchar](max) NULL,
	[REACCIONES_PUB] [varchar](200) NULL,
	[AUTOR_PUB] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PUB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PUBLICACIONES_T]  WITH CHECK ADD  CONSTRAINT [FK_AUTOR] FOREIGN KEY([AUTOR_PUB])
REFERENCES [dbo].[USUARIOS_T] ([ID_US])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PUBLICACIONES_T] CHECK CONSTRAINT [FK_AUTOR]
GO

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HISTORIAL_T](
	[ID_HIST] [int] IDENTITY(1,1) NOT NULL,
	[ID_US_HIST] [int] NULL,
	[ACCION_HIST] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_HIST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HISTORIAL_T]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO] FOREIGN KEY([ID_US_HIST])
REFERENCES [dbo].[USUARIOS_T] ([ID_US])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[HISTORIAL_T] CHECK CONSTRAINT [FK_USUARIO]
GO